name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws/
          echo "$super_secret" > ~/.aws/credentials
        env:
          super_secret: ${{ secrets.AWS_CONFIG }}

      - name: Verify AWS Credentials
        run: cat ~/.aws/credentials

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: List AWS CLI profiles
        run: aws configure list-profiles

      - name: List S3 buckets
        run: aws s3 ls --region eu-central-1 --profile techstarter

      - name: Install npm dependencies
        run: npm install

      - name: Deploy Lambda Function
        run: |
          # npx ncc build index.ts
          # zip -q -j deploy.zip /absolute/path/to/dist/*
          aws lambda update-function-code --function-name=login-google 
          # --zip-file=fileb://deploy.zip
      
